### ISSUE TITLE
create user fial

### ISSUE THREAD

**Issue by Jonny-china** [mrvautin/adminMongo#219]
MongoError: Use of SCRAM-SHA-256 requires undigested passwords

**Comment by Bacto** [comment]
Hi,

Same problem here.

If MongoDB is version 4, we should pass parameter `passwordDigestor: "server"` to avoid this error.

See https://docs.mongodb.com/manual/reference/method/db.createUser/

**Comment by bitmeal** [comment]
Did not see this issue posted, but but dug more into it - presenting a dirty fix - in Issue #227 .
The Problem would best be addressed in the *node-mongo-native* driver but they reject further contributions to the 2.2-branch. See referenced issue for further details.

**Comment by jcc10** [comment]
I listed a temp fix [here](https://github.com/mrvautin/adminMongo/issues/227#issuecomment-506468788). The TL;DR is you replace one line in the `package.json` with the following.

`"mongodb": "bitmeal/node-mongodb-native#2.2",`

**Comment by Tsangares** [comment]
This is still not fixed. I changed the dependency in the package.json like @jcc10  mentioned. 
At line 65 I changed, 

        "mongodb": "^2.2.4",

to,

        "mongodb": "bitmeal/node-mongodb-native#2.2",

With success at creating users. I don't understand what the ultimate issue is, but I am using mongodb 4.4 which is the latest when writing this and the admin panel should work with the latest version. Should we simply just change the package.json or can we change the db create user code to support the hash type?

**Comment by Tsangares** [comment]
Note, even though this created a user, I am unable to authenticate with pymongo, and idk what authMechanism `bitmeal/node-mongodb-native` used
